#!/bin/bash

if [ -d ~/.zensical ]; then
  . ~/.zensical/bin/activate
else
  echo "It appears you are activating zensical virtual environment for the first time."
  echo "The zensical venv will now be set up for you, and then activated. Please report any error(s)."
  python3 -m venv ~/.zensical
  . ~/.zensical/bin/activate
  pip install -r ./requirements.txt
fi

