site_name: AllStarLink Manual
site_url: https://allstarlink.github.io/
site_description: AllStarLink Manual
site_author: AllStarLink Team
plugins:
  - search
  - glightbox
  - print-site
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2025 AllStarLink Inc.
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  logo: assets/allstar-logo-small.png
  favicon: assets/allstarlink.png
  palette:
    scheme: allstarlink
extra_css:
  - stylesheets/extra.css
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/solid/link
      link: https://www.allstarlink.org/
      name: AllStarLink Home
    - icon: fontawesome/brands/github
      link: https://github.com/AllStarLink
      name: AllStarLink on GitHub
nav:
  - Home: index.md
  - Installation:
    - user-guide/index.md
    - "Important Considerations": user-guide/whats-new.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">ASL3 Appliance</span>:
      - user-guide/pi-detailed.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">ASL3 on Debian 12</span>:
      - user-guide/install.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">Post Installation</span>:
      - user-guide/updates.md
      - "Differences & Known Issues": user-guide/known-issues-diffs.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">Allmon3 Install and Config</span>:
      - allmon3/basics.md
      - allmon3/install.md
      - allmon3/config.md
      - allmon3/usermgmt.md
  - Basic Operation:
    - user-guide/menu.md
    - user-guide/asl-cmds-tools.md
    - user-guide/passwords.md
    - user-guide/support.md
    - user-guide/troubleshooting.md
    - user-guide/betatest.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">Pi Appliance Specifics</span>:
      - "Getting Started With Cockpit": pi/cockpit-get-started.md
      - pi/cockpit-basics.md
      - pi/cockpit-console.md
      - pi/cockpit-network.md
      - pi/cockpit-updates.md
      - pi/cockpit-services.md
      - pi/cockpit-firewall.md
  - Advanced Topics:
    - adv-topics/index.md
    - adv-topics/commands.md
    - adv-topics/incompatibles.md
    - adv-topics/allowdenylists.md
    - adv-topics/aprs.md
    - adv-topics/tts.md 
    - adv-topics/conftmpl.md
    - adv-topics/autopatch.md
    - adv-topics/audio-level.md
    - adv-topics/daq.md
    - adv-topics/dns-servers.md
    - adv-topics/eurorptr.md
    - adv-topics/hotspot_hd.md
    - adv-topics/httpreg.md
    - adv-topics/iaxreg.md
    - adv-topics/litz.md
    - adv-topics/macros.md
    - adv-topics/multinodesnetwork.md 
    - adv-topics/noderesolution.md
    - adv-topics/other-software.md
    - adv-topics/permanentnode.md
    - adv-topics/permissions.md
    - adv-topics/privatenodes.md
    - adv-topics/remotebase.md
    - adv-topics/rxtoneburst.md
    - adv-topics/sa818modules.md
    - adv-topics/sip-phone.md
    - adv-topics/sleepmode.md
    - adv-topics/broadcastify.md
    - adv-topics/uefi-secureboot.md
    - adv-topics/usbinterfaces.md
  - VOTER/RTCM:
    - voter/index.md
    - voter/about-voter.md
    - voter/voter-protocol.md
    - voter/voter-chan_voter.md
    - voter/rtcm-hardware.md
    - voter/voter-hardware.md
    - voter/voter-firmware.md
    - voter/voter-gps.md
    - voter/voter-menus.md
    - voter/voter-audio.md
    - voter/voter-buffers.md
    - voter/voter-simulcasting.md
    - voter/voter-audioanalysis.md
    - voter/voter-quantar.md
  - Developer Guide:
    - developers/index.md
    - developers/package-builds.md
    - developers/source-install.md
    - developers/aptly.md
  - Man Pages:
    - mans/index.md
    - mans/allmon3-passwd.md
    - mans/asl-find-sound.md
    - mans/asl-node-lookup.md
    - mans/asl-play-arn.md
    - mans/asl-say.md
    - mans/asl-setup-dkms-mok.md
  - Config Files:
    - config/index.md
    - config/config-structure.md
    - config/rpt_conf.md
    - config/voter_conf.md
