site_name: AllStarLink Manual
site_url: https://allstarlink.github.io/
site_description: AllStarLink Manual
site_author: AllStarLink Team
plugins:
  - search
  - glightbox
  - print-site
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
copyright: Copyright &copy; 2024 AllStarLink Inc.
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  logo: assets/allstar-logo-small.png
  favicon: assets/allstarlink.png
  palette:
    scheme: allstarlink
extra_css:
  - stylesheets/extra.css
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/solid/link
      link: https://www.allstarlink.org/
      name: AllStarLink Home
    - icon: fontawesome/brands/github
      link: https://github.com/AllStarLink
      name: AllStarLink on GitHub
nav:
  - Home: index.md
  - User Guide:
    - user-guide/index.md
    - "What's New?": user-guide/whats-new.md
    - user-guide/pi-detailed.md
    - user-guide/install.md
    - user-guide/menu.md
    - user-guide/updates.md
    - "Differences & Issues": user-guide/known-issues-diffs.md
    - user-guide/passwords.md
    - user-guide/support.md
    - user-guide/betatest.md
    - "Basic Troubleshooting Tips": user-guide/troubleshooting.md 
  - Pi Appliance:
    - pi/index.md
    - pi/cockpit-basics.md
    - pi/cockpit-console.md
    - pi/cockpit-network.md
    - pi/cockpit-updates.md
    - pi/cockpit-services.md
    - pi/cockpit-firewall.md
  - Advanced Topics:
    - adv-topics/index.md
    - adv-topics/commands.md
    - adv-topics/incompatibles.md
    - adv-topics/usbinterfaces.md
    - adv-topics/sa818modules.md
    - adv-topics/conftmpl.md
    - adv-topics/httpreg.md
    - adv-topics/allowdenylists.md
    - adv-topics/other-software.md
    - adv-topics/sip-phone.md
    - adv-topics/broadcastify.md
    - adv-topics/hotspot_hd.md
    - adv-topics/autopatch.md
    - adv-topics/permissions.md
    - adv-topics/noderesolution.md
  - Allmon3:
    - allmon3/index.md
    - allmon3/install.md
    - allmon3/config.md
    - allmon3/usermgmt.md
  - Developer Guide:
    - developers/index.md
    - developers/package-builds.md
    - developers/source-install.md
    - developers/aptly.md
