site_name: AllStarLink Manual
site_url: https://allstarlink.github.io/
site_description: AllStarLink Manual
site_author: AllStarLink Team
plugins:
  - search
  - glightbox
  - print-site
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2025 AllStarLink Inc.
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  logo: assets/allstar-logo-small.png
  favicon: assets/allstarlink.png
  palette:
    scheme: allstarlink
extra_css:
  - stylesheets/extra.css
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/solid/link
      link: https://www.allstarlink.org/
      name: AllStarLink Home
    - icon: fontawesome/brands/github
      link: https://github.com/AllStarLink
      name: AllStarLink on GitHub
nav:
  - Home: index.md
  - Getting Started:
    - basics/index.md
    - basics/gettingstarted.md
    - basics/portal.md
    - basics/standardcommands.md
    - basics/commands.md
    - basics/incompatibles.md
  - Installation:
    - install/index.md
    - install/whats-new.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">ASL3 Appliance (Raspberry Pi)</span>:
      - install/pi-appliance/index.md
      - install/pi-appliance/pi-detailed.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">ASL3 on Debian</span>:
      - install/debian/index.md
      - install/debian/install.md
      - install/debian/deb-appliance.md
      - install/debian/docker.md  
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">Allmon3</span>:
      - allmon3/index.md
      - allmon3/install.md
      - allmon3/config.md
      - allmon3/usermgmt.md
  - Basic Operation:
    - user-guide/index.md
    - user-guide/menu.md
    - user-guide/asl-cmds-tools.md
    - user-guide/passwords.md
    - user-guide/updates.md
    - user-guide/support.md
    - user-guide/troubleshooting.md
    - user-guide/phoneportal.md
    - user-guide/externalapps.md
    - user-guide/betatest.md
    - <span style="color:hsl(86.28, 71.6%, 33.14%)">Pi Appliance Specifics (Cockpit)</span>:
      - pi/index.md
      - pi/cockpit-get-started.md
      - pi/cockpit-basics.md
      - pi/cockpit-console.md
      - pi/cockpit-network.md
      - pi/cockpit-updates.md
      - pi/cockpit-services.md
      - pi/cockpit-firewall.md
  - Advanced Topics:
    - adv-topics/index.md
    - adv-topics/allowdenylists.md
    - adv-topics/aprs.md
    - adv-topics/tts.md 
    - adv-topics/conftmpl.md
    - adv-topics/archivedir.md
    - adv-topics/autopatch.md
    - adv-topics/audio-level.md
    - adv-topics/courtesytones.md
    - adv-topics/condiscpgm.md
    - adv-topics/daq.md
    - adv-topics/dns-servers.md
    - adv-topics/dtmffunctions.md
    - adv-topics/elkelink.md
    - adv-topics/eurorptr.md
    - adv-topics/hotspot_hd.md
    - adv-topics/httpreg.md
    - adv-topics/iaxreg.md
    - adv-topics/linkacttimer.md
    - adv-topics/litz.md
    - adv-topics/macros.md
    - adv-topics/mdc1200.md
    - adv-topics/multinodesnetwork.md
    - adv-topics/nnx.md 
    - adv-topics/noderesolution.md
    - adv-topics/other-software.md
    - adv-topics/parrotmode.md
    - adv-topics/permanentnode.md
    - adv-topics/parrotmode.md
    - adv-topics/permissions.md
    - adv-topics/privatenodes.md
    - adv-topics/remotebase.md
    - adv-topics/rxtoneburst.md
    - adv-topics/sa818modules.md
    - adv-topics/sip-phone.md
    - adv-topics/sleepmode.md
    - adv-topics/soundfiles.md
    - adv-topics/broadcastify.md
    - adv-topics/remotebase.md
    - adv-topics/rxtoneburst.md
    - adv-topics/telemetry.md
    - adv-topics/tlb.md
    - adv-topics/tonemacros.md
    - adv-topics/tonesignalling.md
    - adv-topics/uefi-secureboot.md
    - adv-topics/usbinterfaces.md
  - VOTER/RTCM:
    - voter/index.md
    - voter/about-voter.md
    - voter/voter-protocol.md
    - voter/voter-chan_voter.md
    - voter/rtcm-hardware.md
    - voter/voter-hardware.md
    - voter/voter-firmware.md
    - voter/voter-gps.md
    - voter/voter-menus.md
    - voter/voter-audio.md
    - voter/voter-buffers.md
    - voter/voter-simulcasting.md
    - voter/voter-audioanalysis.md
    - voter/voter-quantar.md
  - Developer Guide:
    - developers/index.md
    - developers/package-builds.md
    - developers/source-code.md
    - developers/source-install.md
    - developers/aptly.md
    - developers/versioning.md
  - Man Pages:
    - mans/index.md
    - mans/allmon3-passwd.md
    - mans/asl-find-sound.md
    - mans/asl-node-lookup.md
    - mans/asl-play-arn.md
    - mans/asl-say.md
    - mans/asl-setup-dkms-mok.md
  - Config Files:
    - config/index.md
    - config/config-structure.md
    - config/extensions_conf.md
    - config/iax_conf.md
    - config/rpt_conf.md
    - config/tlb_conf.md
    - config/voter_conf.md
