name: "Pre-commit checks"

on:
   pull_request:
      types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
   codespell:
    name: "Check for spelling errors"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          ignore_words_file: ./.codespellignore
          # When using this Action in other repos, the --skip option below can be removed
          # and the .codespellignore file can be used to ignore files or words.          
